Домашняя работа к lesson_4
eugene-okulik/shaminda pull request #3
Opened 2024-12-23 21:45 UTC by DaShamin666

2024-12-24 06:51 UTC, eugene-okulik requested changes
Всё отлично, но проверку на внимательность не прошел ))

2024-12-24 06:51 UTC, eugene-okulik commented on homework/home_work_lesson_4/basics_2.py
> +my_dict['dict']['i am a tuple'] = 'new value'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-12-24 06:58 UTC, DaShamin666 commented on homework/home_work_lesson_4/basics_2.py
> +my_dict['dict']['i am a tuple'] = 'new value'
понял , да видимо не так понял задание, спасибо что обтяснили )) сейчас перезалю исправленную

2024-12-24 17:41 UTC, DaShamin666 commented on homework/home_work_lesson_4/basics_2.py
> +my_dict['dict']['i am a tuple'] = 'new value'
перезалил, все ли правильно понял и сделал?

2024-12-25 09:07 UTC, DaShamin666 commented on homework/home_work_lesson_4/basics_2.py
> +my_dict['dict']['i am a tuple'] = 'new value'
?

2024-12-25 10:04 UTC, eugene-okulik approved these changes
:+1:

2024-12-25 10:04 UTC, merged