Home_work_6
eugene-okulik/shaminda pull request #5
Opened 2024-12-26 22:01 UTC by DaShamin666

2024-12-27 06:58 UTC, eugene-okulik requested changes

2024-12-27 06:58 UTC, eugene-okulik commented on homework/home_work_lesson_6/home_work.py
знаки препинания пропали:
```
Etiaming tincidunting nequeing erating quising molestieing eniming imperdieting veling Integering urnaing nisling facilisising vitaeing sempering ating dignissiming vitaeing liberoing
```

2024-12-27 14:04 UTC, DaShamin666 commented on homework/home_work_lesson_6/home_work.py
не правильно понял задание , думал они просто не нужны , исправил , згааки препинания остались

2024-12-28 09:13 UTC, eugene-okulik approved these changes

2024-12-28 09:13 UTC, merged